<?php
/**
 * @name Index.php
 * @desc
 * @author 胡扬星
 * @createtime : 2018/1/8
 */
class indexController extends  common\admin {
        function init()
        {
            parent::init(); // TODO: Change the autogenerated stub
        }
        public function indexAction()
        {
            $data = '';
            $this->getView()->assign('data',$data)->display('index/index.html');
        }
 }