<?php
/**
 * @name nav.php
 * @desc
 * @author 胡扬星
 * @createtime : 2018/1/17
 */
class navController extends \common\admin{
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function listsAction()
    {

    }
}